# Program1 - Header1

## Program1 - Header2

### Program1 - Header3

#### Program1 - Header4

##### Program1 - Header5

###### Program1 - Header6

In [1]:
print("Hello World")

Hello World


In [2]:
num = 100
print(num)

100


In [3]:
num

100

In [4]:
print(f"num = {num}")
# formatted string literal
# anything { } is evaluated as python code

num = 100


In [5]:
a=10
b=20
print(a+b)

30


In [6]:
# common shotcuts
# esc + a --> add a cell above the current cell
# esc + b --> add a cell below the current cell
# enter --> set focus inside the current cell and you can enter character
# esc + dd --> delete the current cell
# esc + m --> convert the type of the cell to markdown
# esc + y --> convert the type of the cell to code
# shift + enter --> execute the current cell and add a cell below it
# tab --> show the intelliscence

### numpy array creation example, array() and print the properties

In [7]:
import numpy as np

In [8]:
def function1():
    arr1 = [10,20,30,40,50]
    print(arr1)
    print(f"Type = {type(arr1)}")
    print(f"arr1[0]Type = {type(arr1[0])}")

In [9]:
  function1()

[10, 20, 30, 40, 50]
Type = <class 'list'>
arr1[0]Type = <class 'int'>


In [10]:
def function2():
    n_array = np.array([11,22,33,44,55])
    print(n_array)
    print(f"Type = {type(n_array)}")

In [11]:
function2()

[11 22 33 44 55]
Type = <class 'numpy.ndarray'>


In [12]:
def function3():
    arr = np.array([10,20,30,40,50,60])
    print(arr)
    print(f"Type = {type(arr)}")
    print(f"DType = {arr.dtype}")
    print(f"Item size = {arr.itemsize}")
    print(f"Size = {arr.size}")
    print(f"NDIM = {arr.ndim}")
    print(f"NBYTES = {arr.nbytes}")

In [13]:
function3()

[10 20 30 40 50 60]
Type = <class 'numpy.ndarray'>
DType = int64
Item size = 8
Size = 6
NDIM = 1
NBYTES = 48


In [14]:
def printProperties(arr):
    print(arr)
    print(f"Type = {type(arr)}")
    print(f"DType = {arr.dtype}")
    print(f"Item size = {arr.itemsize}")
    print(f"Size = {arr.size}")
    print(f"NDIM = {arr.ndim}")
    print(f"NBYTES = {arr.nbytes}")
n1 = np.array([2,5,8,9,3,4])
printProperties(n1)

[2 5 8 9 3 4]
Type = <class 'numpy.ndarray'>
DType = int64
Item size = 8
Size = 6
NDIM = 1
NBYTES = 48


In [15]:
n3 = np.array([11,22,33,44],dtype = np.int32)
printProperties(n3)

[11 22 33 44]
Type = <class 'numpy.ndarray'>
DType = int32
Item size = 4
Size = 4
NDIM = 1
NBYTES = 16


In [16]:
n4= np.array([1.15,2.31,3.8])
printProperties(n4)

[1.15 2.31 3.8 ]
Type = <class 'numpy.ndarray'>
DType = float64
Item size = 8
Size = 3
NDIM = 1
NBYTES = 24


In [17]:
n5 = np.array(["C","C++","Java","Python"])
printProperties(n5)

['C' 'C++' 'Java' 'Python']
Type = <class 'numpy.ndarray'>
DType = <U6
Item size = 24
Size = 4
NDIM = 1
NBYTES = 96


In [18]:
country=np.array(["India","USA","Australia"])
printProperties(country)

['India' 'USA' 'Australia']
Type = <class 'numpy.ndarray'>
DType = <U9
Item size = 36
Size = 3
NDIM = 1
NBYTES = 108


## Indexing,Slicing,reshape

In [19]:
# if you are making a new file
# import numpy as np

In [20]:
n1 = np.array([11,22,33,44,55,66,77,88])
print(n1)

[11 22 33 44 55 66 77 88]


In [21]:
print(n1[2])    # positive indexing

33


In [22]:
print(len(n1))   # no of elements in the array

8


In [23]:
print(n1[4])      # positive indexing

55


In [24]:
print(n1[-1])     # negative indexing

88


In [25]:
print(n1[-8])     # negative indexing

11


In [26]:
print(n1[0])     # positive indexing

11


In [27]:
print(n1[2:5])    # start[2]= slicing starts      stop[5]=slicing will end at 5(but the last index is not included in the output)

[33 44 55]


In [28]:
print(f"NDIM ={n1.ndim}" )

NDIM =1


In [29]:
print(f"Shape = {n1.shape}")

Shape = (8,)


In [30]:
n1= n1.reshape([4,2])
print(n1)

[[11 22]
 [33 44]
 [55 66]
 [77 88]]


In [31]:
print(f"NDIM ={n1.ndim}" )

NDIM =2


In [32]:
print(f"Shape = {n1.shape}")

Shape = (4, 2)


## zeros(),ones(),arange(),random()

In [33]:
# import numpy as np

In [34]:
arr1=np.arange(0,10)
print(arr1)

[0 1 2 3 4 5 6 7 8 9]


In [35]:
arr1=np.arange(10,25,2)
print(arr1)

[10 12 14 16 18 20 22 24]


In [36]:
arr1=np.arange(1,10,2)
print(arr1)

[1 3 5 7 9]


In [37]:
arr2=np.zeros(5)
print(arr2)

[0. 0. 0. 0. 0.]


In [38]:
arr2=np.ones(5)
print(arr2)

[1. 1. 1. 1. 1.]


In [39]:
n1=np.array([11,22,33,44])
n2=np.array([10,20,30,40])
print(f"N1 = {n1}")
print(f"N2 = {n2}")
print(n1+n2)

N1 = [11 22 33 44]
N2 = [10 20 30 40]
[21 42 63 84]


In [40]:
n1=np.random.random(5)      # generate any random 5 floating-point numbers 
print(n1)                   # each number is between 0.0 to 1.0(1.0 not included)

[0.73294709 0.23124137 0.73869781 0.0611146  0.1615011 ]


In [41]:
n4=np.random.randint(1,10,4)       # any four integer numbers are randomly generated between 1 to 10       
print(n4)   

[3 4 3 3]


In [42]:
n1=np.array([11,22,33,44])     
print(n1*5)                       # broadcast operation

[ 55 110 165 220]


In [43]:
n1=np.array([10,20,30,40,50])  
print(f"n1[[false,false,true,true,false]]={n1[[False,False,True,True,False]]}")

n1[[false,false,true,true,false]]=[30 40]
